# Generated by Django 4.2.18 on 2025-01-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MnemonicBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, verbose_name="设备ID")),
                ("encrypted_mnemonic", models.TextField(verbose_name="加密助记词")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "助记词备份",
                "verbose_name_plural": "助记词备份",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=100, verbose_name="创建设备ID"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="钱包名称")),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("BNB", "BNB Chain"),
                            ("AVAX", "Avalanche"),
                            ("SOL", "Solana"),
                            ("MATIC", "Polygon"),
                        ],
                        max_length=10,
                        verbose_name="区块链",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="钱包地址")),
                ("encrypted_private_key", models.TextField(verbose_name="加密私钥")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="wallet_avatars/",
                        verbose_name="钱包头像",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
                "ordering": ["-created_at"],
                "unique_together": {("device_id", "chain", "address")},
            },
        ),
    ]
