# Generated by Django 4.2.18 on 2025-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(
                choices=[
                    ('TRANSFER', '转账'),
                    ('APPROVE', '授权'),
                    ('SWAP', '兑换'),
                    ('MINT', '铸造'),
                    ('BURN', '销毁'),
                    ('NFT_TRANSFER', 'NFT转账'),
                    ('OTHER', '其他'),
                ],
                max_length=20,
                verbose_name='交易类型',
            ),
        ),
    ] 