# Generated by Django 4.2.18 on 2025-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="metaplex_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Metaplex Data"),
        ),
    ]
