# Generated by Django 4.2.18 on 2025-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coin_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="币种ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("symbol", models.CharField(max_length=20, verbose_name="符号")),
                ("rank", models.IntegerField(default=0, verbose_name="排名")),
                ("is_new", models.BooleanField(default=False, verbose_name="是否新币")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "type",
                    models.CharField(
                        default="token", max_length=20, verbose_name="类型"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "代币索引",
                "verbose_name_plural": "代币索引",
                "ordering": ["rank"],
            },
        ),
    ]
