# Generated by Django 4.2.18 on 2025-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralrelationship",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="referralrelationship",
            name="wallet_refe_referre_149770_idx",
        ),
        migrations.RemoveIndex(
            model_name="referralrelationship",
            name="wallet_refe_referre_3505cd_idx",
        ),
        migrations.RemoveField(
            model_name="referralrelationship",
            name="wallet_created",
        ),
        migrations.RemoveField(
            model_name="referralrelationship",
            name="wallet_points_awarded",
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="download_completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="download_points_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="referred_device_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="referrer_device_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
