# Generated by Django 4.2.18 on 2025-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.CharField(default="0", max_length=64),
        ),
    ]
