# Generated by Django 4.2.18 on 2025-04-10 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_token_metaplex_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_address",
                    models.CharField(help_text="代币地址", max_length=100),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
            ],
            options={
                "verbose_name": "隐藏代币",
                "verbose_name_plural": "隐藏代币",
                "db_table": "hidden_token",
            },
        ),
        migrations.DeleteModel(
            name="MnemonicBackup",
        ),
        migrations.AlterUniqueTogether(
            name="nftcollection",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="PointsHistory",
        ),
        migrations.DeleteModel(
            name="ReferralLink",
        ),
        migrations.DeleteModel(
            name="ReferralRelationship",
        ),
        migrations.RemoveField(
            model_name="sharetasktoken",
            name="task",
        ),
        migrations.RemoveField(
            model_name="sharetasktoken",
            name="token",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="task",
        ),
        migrations.AlterUniqueTogether(
            name="tokenindex",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tokenindexgrade",
            name="token",
        ),
        migrations.RemoveField(
            model_name="tokenindexmetrics",
            name="token",
        ),
        migrations.DeleteModel(
            name="TokenIndexReport",
        ),
        migrations.DeleteModel(
            name="TokenIndexSource",
        ),
        migrations.DeleteModel(
            name="UserPoints",
        ),
        migrations.AlterModelOptions(
            name="token",
            options={"verbose_name": "代币", "verbose_name_plural": "代币"},
        ),
        migrations.RemoveIndex(
            model_name="token",
            name="wallet_toke_chain_298ab4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="paymentpassword",
            name="biometric_verified_at",
        ),
        migrations.RemoveField(
            model_name="paymentpassword",
            name="is_biometric_enabled",
        ),
        migrations.RemoveField(
            model_name="token",
            name="block_number",
        ),
        migrations.RemoveField(
            model_name="token",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="token",
            name="category",
        ),
        migrations.RemoveField(
            model_name="token",
            name="circulating_supply",
        ),
        migrations.RemoveField(
            model_name="token",
            name="coingecko_id",
        ),
        migrations.RemoveField(
            model_name="token",
            name="contract_type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="description",
        ),
        migrations.RemoveField(
            model_name="token",
            name="discord",
        ),
        migrations.RemoveField(
            model_name="token",
            name="email",
        ),
        migrations.RemoveField(
            model_name="token",
            name="fully_diluted_valuation",
        ),
        migrations.RemoveField(
            model_name="token",
            name="github",
        ),
        migrations.RemoveField(
            model_name="token",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_native",
        ),
        migrations.RemoveField(
            model_name="token",
            name="last_balance",
        ),
        migrations.RemoveField(
            model_name="token",
            name="last_price",
        ),
        migrations.RemoveField(
            model_name="token",
            name="last_price_change",
        ),
        migrations.RemoveField(
            model_name="token",
            name="last_value",
        ),
        migrations.RemoveField(
            model_name="token",
            name="logo_hash",
        ),
        migrations.RemoveField(
            model_name="token",
            name="market_cap",
        ),
        migrations.RemoveField(
            model_name="token",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="token",
            name="metaplex_data",
        ),
        migrations.RemoveField(
            model_name="token",
            name="moralis",
        ),
        migrations.RemoveField(
            model_name="token",
            name="possible_spam",
        ),
        migrations.RemoveField(
            model_name="token",
            name="reddit",
        ),
        migrations.RemoveField(
            model_name="token",
            name="security_score",
        ),
        migrations.RemoveField(
            model_name="token",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="token",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="token",
            name="total_supply",
        ),
        migrations.RemoveField(
            model_name="token",
            name="total_supply_formatted",
        ),
        migrations.RemoveField(
            model_name="token",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="token",
            name="type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="validated",
        ),
        migrations.RemoveField(
            model_name="token",
            name="website",
        ),
        migrations.AddField(
            model_name="token",
            name="is_active",
            field=models.BooleanField(default=True, help_text="是否激活"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=0, default=0, help_text="手续费(原始值)", max_digits=65
            ),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="device_id",
            field=models.CharField(help_text="设备ID", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="encrypted_password",
            field=models.CharField(help_text="加密后的支付密码", max_length=500),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="更新时间"),
        ),
        migrations.AlterField(
            model_name="token",
            name="address",
            field=models.CharField(help_text="代币合约地址", max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("BSC", "BNB Chain"),
                    ("MATIC", "Polygon"),
                    ("SOL", "Solana"),
                ],
                help_text="区块链类型",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="decimals",
            field=models.IntegerField(help_text="小数位数"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_recommended",
            field=models.BooleanField(default=False, help_text="是否推荐"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="是否已验证"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_visible",
            field=models.BooleanField(default=True, help_text="是否可见"),
        ),
        migrations.AlterField(
            model_name="token",
            name="logo",
            field=models.URLField(
                blank=True, help_text="代币logo", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(help_text="代币名称", max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(help_text="代币符号", max_length=20),
        ),
        migrations.AlterField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="更新时间"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, help_text="交易金额(原始值)", max_digits=65
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_number",
            field=models.BigIntegerField(help_text="区块号"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_timestamp",
            field=models.DateTimeField(help_text="区块时间"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_address",
            field=models.CharField(help_text="发送地址", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.BooleanField(default=True, help_text="交易状态"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(help_text="接收地址", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_token_address",
            field=models.CharField(
                blank=True,
                help_text="目标代币地址(SWAP场景)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="token",
            field=models.ForeignKey(
                help_text="代币",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wallet.token",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="token_info",
            field=models.JSONField(
                blank=True, help_text="代币信息(SWAP等场景)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(help_text="交易哈希", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "转账"),
                    ("SWAP", "兑换"),
                    ("APPROVE", "授权"),
                    ("CONTRACT", "合约调用"),
                ],
                help_text="交易类型",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                help_text="关联钱包",
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(help_text="钱包地址", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(
                choices=[
                    ("ETH", "Ethereum"),
                    ("BSC", "BNB Chain"),
                    ("MATIC", "Polygon"),
                    ("SOL", "Solana"),
                ],
                help_text="区块链类型",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="device_id",
            field=models.CharField(help_text="设备ID", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="encrypted_private_key",
            field=models.TextField(blank=True, help_text="加密后的私钥", null=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(default=True, help_text="是否激活"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_imported",
            field=models.BooleanField(default=False, help_text="是否导入的钱包"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_watch_only",
            field=models.BooleanField(default=False, help_text="是否仅观察"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(help_text="钱包名称", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="更新时间"),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("device_id", "address")},
        ),
        migrations.AlterModelTable(
            name="paymentpassword",
            table="payment_password",
        ),
        migrations.AlterModelTable(
            name="token",
            table="token",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transaction",
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallet",
        ),
        migrations.DeleteModel(
            name="ShareTaskToken",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskHistory",
        ),
        migrations.DeleteModel(
            name="TokenCategory",
        ),
        migrations.DeleteModel(
            name="TokenIndex",
        ),
        migrations.DeleteModel(
            name="TokenIndexGrade",
        ),
        migrations.DeleteModel(
            name="TokenIndexMetrics",
        ),
        migrations.AddField(
            model_name="hiddentoken",
            name="wallet",
            field=models.ForeignKey(
                help_text="关联钱包",
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gas_price",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gas_used",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="nft_collection",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="nft_token_id",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="referral_info",
        ),
        migrations.DeleteModel(
            name="NFTCollection",
        ),
        migrations.AlterUniqueTogether(
            name="hiddentoken",
            unique_together={("wallet", "token_address")},
        ),
    ]
