# Generated by Django 4.2.18 on 2025-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="设备ID"
                    ),
                ),
                ("total_points", models.IntegerField(default=0, verbose_name="总积分")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户积分",
                "verbose_name_plural": "用户积分",
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="wallet_user_device__dfd57c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer_device_id",
                    models.CharField(max_length=100, verbose_name="推荐人设备ID"),
                ),
                (
                    "referred_device_id",
                    models.CharField(max_length=100, verbose_name="被推荐人设备ID"),
                ),
                (
                    "download_completed",
                    models.BooleanField(default=True, verbose_name="是否完成下载"),
                ),
                (
                    "wallet_created",
                    models.BooleanField(
                        default=False, verbose_name="是否创建/导入钱包"
                    ),
                ),
                (
                    "download_points_awarded",
                    models.BooleanField(
                        default=False, verbose_name="是否已奖励下载积分"
                    ),
                ),
                (
                    "wallet_points_awarded",
                    models.BooleanField(
                        default=False, verbose_name="是否已奖励创建钱包积分"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "推荐关系",
                "verbose_name_plural": "推荐关系",
                "indexes": [
                    models.Index(
                        fields=["referrer_device_id"],
                        name="wallet_refe_referre_149770_idx",
                    ),
                    models.Index(
                        fields=["referred_device_id"],
                        name="wallet_refe_referre_3505cd_idx",
                    ),
                ],
                "unique_together": {("referrer_device_id", "referred_device_id")},
            },
        ),
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, verbose_name="设备ID")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="推荐码"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                ("clicks", models.IntegerField(default=0, verbose_name="点击次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "推荐链接",
                "verbose_name_plural": "推荐链接",
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="wallet_refe_device__5ea9b3_idx"
                    ),
                    models.Index(fields=["code"], name="wallet_refe_code_566f65_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, verbose_name="设备ID")),
                ("points", models.IntegerField(verbose_name="积分变动")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DOWNLOAD_REFERRAL", "下载推荐"),
                            ("WALLET_REFERRAL", "钱包创建推荐"),
                            ("POINTS_USED", "积分使用"),
                            ("ADMIN_ADJUSTMENT", "管理员调整"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "related_device_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="相关设备ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "积分历史",
                "verbose_name_plural": "积分历史",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="wallet_poin_device__6fe442_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="wallet_poin_action__59a4af_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="wallet_poin_created_0707cf_idx"
                    ),
                ],
            },
        ),
    ]
