# Generated by Django 4.2.18 on 2025-03-25 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_referralrelationship_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("FIRST_TRANSFER", "首次转账"),
                            ("FIRST_SWAP", "首次兑换"),
                            ("CREATE_WALLET", "创建钱包"),
                            ("SHARE_TOKEN", "分享代币"),
                            ("INVITE_DOWNLOAD", "邀请下载"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("points", models.IntegerField()),
                ("is_repeatable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stages_config", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ShareTaskToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=3)),
                ("daily_limit", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tasks",
                        to="wallet.token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Task Token",
                "verbose_name_plural": "Share Task Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(null=True)),
                ("points_awarded", models.BooleanField(default=False)),
                ("extra_data", models.JSONField(null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Task",
                "verbose_name_plural": "User Tasks",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="wallet_user_device__43e88c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="wallet_user_status_d735e3_idx"
                    ),
                ],
            },
        ),
    ]
