# Generated by Django 4.2.18 on 2025-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_paymentpassword"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_imported",
            field=models.BooleanField(default=False, verbose_name="是否导入的钱包"),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_watch_only",
            field=models.BooleanField(default=False, verbose_name="是否观察者钱包"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(max_length=100, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="wallet_avatars/", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(max_length=20, verbose_name="区块链"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="device_id",
            field=models.CharField(max_length=100, verbose_name="设备ID"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="encrypted_private_key",
            field=models.TextField(blank=True, null=True, verbose_name="加密私钥"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=100, verbose_name="钱包名称"),
        ),
    ]
