# Generated by Django 4.2.18 on 2025-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_tokenindex_coin_id_alter_tokenindex_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenindex",
            name="is_token_synced",
            field=models.BooleanField(
                default=False,
                help_text="代币详细信息是否已同步",
                verbose_name="代币已同步",
            ),
        ),
    ]
