# Generated by Django 4.2.18 on 2025-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_hiddentoken_delete_mnemonicbackup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="钱包头像", null=True, upload_to="wallet_avatars/"
            ),
        ),
    ]
