# Generated by Django 4.2.18 on 2025-03-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_task_sharetasktoken_usertask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mnemonicbackup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "助记词备份",
                "verbose_name_plural": "助记词备份",
            },
        ),
        migrations.AlterModelOptions(
            name="nftcollection",
            options={
                "ordering": ["-floor_price_usd", "-created_at"],
                "verbose_name": "NFT合集",
                "verbose_name_plural": "NFT合集",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentpassword",
            options={"verbose_name": "支付密码", "verbose_name_plural": "支付密码"},
        ),
        migrations.AlterModelOptions(
            name="pointshistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "积分历史",
                "verbose_name_plural": "积分历史",
            },
        ),
        migrations.AlterModelOptions(
            name="referrallink",
            options={"verbose_name": "推荐链接", "verbose_name_plural": "推荐链接"},
        ),
        migrations.AlterModelOptions(
            name="referralrelationship",
            options={"verbose_name": "推荐关系", "verbose_name_plural": "推荐关系"},
        ),
        migrations.AlterModelOptions(
            name="sharetasktoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "分享任务代币",
                "verbose_name_plural": "分享任务代币",
            },
        ),
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ["-is_recommended", "-is_verified", "-created_at"],
                "verbose_name": "代币",
                "verbose_name_plural": "代币",
            },
        ),
        migrations.AlterModelOptions(
            name="tokencategory",
            options={
                "ordering": ["priority", "name"],
                "verbose_name": "代币分类",
                "verbose_name_plural": "代币分类",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindex",
            options={"verbose_name": "代币索引", "verbose_name_plural": "代币索引"},
        ),
        migrations.AlterModelOptions(
            name="tokenindexgrade",
            options={"verbose_name": "代币评级", "verbose_name_plural": "代币评级"},
        ),
        migrations.AlterModelOptions(
            name="tokenindexmetrics",
            options={"verbose_name": "代币指标", "verbose_name_plural": "代币指标"},
        ),
        migrations.AlterModelOptions(
            name="tokenindexreport",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "代币库报告",
                "verbose_name_plural": "代币库报告",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindexsource",
            options={
                "ordering": ["priority"],
                "verbose_name": "代币数据源",
                "verbose_name_plural": "代币数据源",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-block_timestamp"],
                "verbose_name": "交易记录",
                "verbose_name_plural": "交易记录",
            },
        ),
        migrations.AlterModelOptions(
            name="userpoints",
            options={"verbose_name": "用户积分", "verbose_name_plural": "用户积分"},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
            },
        ),
        migrations.RenameField(
            model_name="token",
            old_name="verified",
            new_name="is_verified",
        ),
    ]
