# Generated by Django 4.2.18 on 2025-03-23 10:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_userpoints_referralrelationship_referrallink_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mnemonicbackup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mnemonic Backup",
                "verbose_name_plural": "Mnemonic Backups",
            },
        ),
        migrations.AlterModelOptions(
            name="nftcollection",
            options={
                "ordering": ["-floor_price_usd", "-created_at"],
                "verbose_name": "NFT Collection",
                "verbose_name_plural": "NFT Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentpassword",
            options={
                "verbose_name": "Payment Password",
                "verbose_name_plural": "Payment Passwords",
            },
        ),
        migrations.AlterModelOptions(
            name="pointshistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Points History",
                "verbose_name_plural": "Points History",
            },
        ),
        migrations.AlterModelOptions(
            name="referrallink",
            options={
                "verbose_name": "Recommendation Link",
                "verbose_name_plural": "Recommendation Links",
            },
        ),
        migrations.AlterModelOptions(
            name="referralrelationship",
            options={
                "verbose_name": "Recommendation Relationship",
                "verbose_name_plural": "Recommendation Relationships",
            },
        ),
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ["-is_recommended", "-verified", "-created_at"],
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="tokencategory",
            options={
                "ordering": ["priority", "name"],
                "verbose_name": "Token Category",
                "verbose_name_plural": "Token Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindex",
            options={
                "verbose_name": "Token Index",
                "verbose_name_plural": "Token Indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindexgrade",
            options={
                "verbose_name": "Token Grade",
                "verbose_name_plural": "Token Grades",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindexmetrics",
            options={
                "verbose_name": "Token Metrics",
                "verbose_name_plural": "Token Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindexreport",
            options={
                "ordering": ["-report_date"],
                "verbose_name": "Index Library Report",
                "verbose_name_plural": "Index Library Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenindexsource",
            options={
                "ordering": ["priority"],
                "verbose_name": "Token Data Source",
                "verbose_name_plural": "Token Data Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-block_timestamp"],
                "verbose_name": "Transaction Record",
                "verbose_name_plural": "Transaction Records",
            },
        ),
        migrations.AlterModelOptions(
            name="userpoints",
            options={
                "verbose_name": "User Points",
                "verbose_name_plural": "User Points",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.AddField(
            model_name="wallet",
            name="referral_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mnemonicbackup",
            name="chain",
            field=models.CharField(max_length=20, verbose_name="Blockchain"),
        ),
        migrations.AlterField(
            model_name="mnemonicbackup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="mnemonicbackup",
            name="device_id",
            field=models.CharField(max_length=100, verbose_name="Device ID"),
        ),
        migrations.AlterField(
            model_name="mnemonicbackup",
            name="encrypted_mnemonic",
            field=models.TextField(verbose_name="Encrypted Mnemonic"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="chain",
            field=models.CharField(max_length=20, verbose_name="Blockchain"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="contract_address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contract Address"
            ),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="contract_type",
            field=models.CharField(
                default="ERC721", max_length=20, verbose_name="Contract Type"
            ),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="floor_price",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="Floor Price",
            ),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="floor_price_currency",
            field=models.CharField(
                default="eth", max_length=10, verbose_name="Floor Price Currency"
            ),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="floor_price_usd",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="Floor Price (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="is_spam",
            field=models.BooleanField(default=False, verbose_name="Is Spam"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Collection Name"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="symbol",
            field=models.CharField(max_length=100, verbose_name="Collection Symbol"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="biometric_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Last Biometric Password Verification Time",
            ),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="device_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Device ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="encrypted_password",
            field=models.CharField(
                max_length=255, verbose_name="Encrypted Payment Password"
            ),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="is_biometric_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Is Biometric Enabled"
            ),
        ),
        migrations.AlterField(
            model_name="paymentpassword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("DOWNLOAD_REFERRAL", "Download Recommendation"),
                    ("WALLET_REFERRAL", "Wallet Creation Recommendation"),
                    ("POINTS_USED", "Points Used"),
                    ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Action Type",
            ),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="device_id",
            field=models.CharField(max_length=100, verbose_name="Device ID"),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="points",
            field=models.IntegerField(verbose_name="Points Change"),
        ),
        migrations.AlterField(
            model_name="pointshistory",
            name="related_device_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Related Device ID"
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="clicks",
            field=models.IntegerField(default=0, verbose_name="Click Count"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Recommendation Code"
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="device_id",
            field=models.CharField(max_length=100, verbose_name="Device ID"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="download_completed",
            field=models.BooleanField(
                default=True, verbose_name="Is Download Completed"
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="download_points_awarded",
            field=models.BooleanField(
                default=False, verbose_name="Is Download Points Awarded"
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="referred_device_id",
            field=models.CharField(max_length=100, verbose_name="Referred Device ID"),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="referrer_device_id",
            field=models.CharField(max_length=100, verbose_name="Referrer Device ID"),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="wallet_created",
            field=models.BooleanField(
                default=False, verbose_name="Is Wallet Created/Imported"
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="wallet_points_awarded",
            field=models.BooleanField(
                default=False, verbose_name="Is Wallet Points Awarded"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Contract Address"),
        ),
        migrations.AlterField(
            model_name="token",
            name="block_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Block Height"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="categories",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Categories"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tokens",
                to="wallet.tokencategory",
                verbose_name="Token Category",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="chain",
            field=models.CharField(max_length=10, verbose_name="Chain"),
        ),
        migrations.AlterField(
            model_name="token",
            name="circulating_supply",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Circulating Supply"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="contract_type",
            field=models.CharField(
                default="ERC20", max_length=20, verbose_name="Contract Type"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Created Time"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="decimals",
            field=models.IntegerField(default=18, verbose_name="Decimal Places"),
        ),
        migrations.AlterField(
            model_name="token",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="token",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="fully_diluted_valuation",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Fully Diluted Valuation",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_native",
            field=models.BooleanField(default=False, verbose_name="Is Native Token"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="Is Recommended"),
        ),
        migrations.AlterField(
            model_name="token",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="token",
            name="last_balance",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Balance"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="last_price",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Price"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="last_price_change",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Last 24h Price Change",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="last_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Value"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="logo_hash",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Logo Hash"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="market_cap",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Market Cap"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="token",
            name="possible_spam",
            field=models.BooleanField(default=False, verbose_name="Is Possible Spam"),
        ),
        migrations.AlterField(
            model_name="token",
            name="security_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Security Score"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(max_length=50, verbose_name="Symbol"),
        ),
        migrations.AlterField(
            model_name="token",
            name="thumbnail",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_supply",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Total Supply"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_supply_formatted",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Formatted Total Supply",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.CharField(default="token", max_length=20, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="token",
            name="validated",
            field=models.IntegerField(default=0, verbose_name="Validation Status"),
        ),
        migrations.AlterField(
            model_name="token",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="token",
            name="website",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Website"
            ),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Category Code"
            ),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Category Description"
            ),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="icon",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Category Icon"
            ),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="Display Priority"),
        ),
        migrations.AlterField(
            model_name="tokencategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Contract Address"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="chain",
            field=models.CharField(max_length=10, verbose_name="Chain"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="decimals",
            field=models.IntegerField(default=18, verbose_name="Decimal Places"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="is_native",
            field=models.BooleanField(default=False, verbose_name="Is Native Token"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="symbol",
            field=models.CharField(max_length=50, verbose_name="Symbol"),
        ),
        migrations.AlterField(
            model_name="tokenindex",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="tokenindexgrade",
            name="evaluation_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Evaluation Reason"
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexgrade",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A Grade - Core Token"),
                    ("B", "B Grade - Regular Token"),
                    ("C", "C Grade - Observation Token"),
                ],
                max_length=1,
                verbose_name="Grade",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexgrade",
            name="last_evaluated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Last Evaluation Time"
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexgrade",
            name="score",
            field=models.IntegerField(default=0, verbose_name="Overall Score"),
        ),
        migrations.AlterField(
            model_name="tokenindexgrade",
            name="token",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="wallet.tokenindex",
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="daily_volume",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="24h Transaction Volume (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="holder_count",
            field=models.IntegerField(default=0, verbose_name="Holder Count"),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="liquidity",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="Liquidity (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="market_cap",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="Market Cap (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="price",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="Price (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="token",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="wallet.tokenindex",
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="tokenindexmetrics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="details",
            field=models.JSONField(default=dict, verbose_name="Details"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="grade_a_count",
            field=models.IntegerField(verbose_name="A Grade Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="grade_b_count",
            field=models.IntegerField(verbose_name="B Grade Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="grade_c_count",
            field=models.IntegerField(verbose_name="C Grade Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="new_tokens",
            field=models.IntegerField(verbose_name="New Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="removed_tokens",
            field=models.IntegerField(verbose_name="Removed Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="report_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Report Time"),
        ),
        migrations.AlterField(
            model_name="tokenindexreport",
            name="total_tokens",
            field=models.IntegerField(verbose_name="Total Tokens"),
        ),
        migrations.AlterField(
            model_name="tokenindexsource",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="tokenindexsource",
            name="last_sync",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Sync Time"),
        ),
        migrations.AlterField(
            model_name="tokenindexsource",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Data Source Name"),
        ),
        migrations.AlterField(
            model_name="tokenindexsource",
            name="priority",
            field=models.IntegerField(verbose_name="Priority"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_number",
            field=models.IntegerField(verbose_name="Block Height"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_timestamp",
            field=models.DateTimeField(verbose_name="Block Time"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="chain",
            field=models.CharField(max_length=20, verbose_name="Blockchain"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_address",
            field=models.CharField(max_length=100, verbose_name="From Address"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_price",
            field=models.DecimalField(
                decimal_places=18, max_digits=30, verbose_name="Gas Price"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_used",
            field=models.DecimalField(
                decimal_places=18, max_digits=30, verbose_name="Gas Used"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nft_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wallet.nftcollection",
                verbose_name="NFT Collection",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(max_length=100, verbose_name="To Address"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_token_address",
            field=models.CharField(
                blank=True,
                help_text="Target Token Address (for Swap transaction)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wallet.token",
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="token_info",
            field=models.JSONField(blank=True, null=True, verbose_name="Token Info"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_hash",
            field=models.CharField(max_length=100, verbose_name="Transaction Hash"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transfer"),
                    ("APPROVE", "Approve"),
                    ("SWAP", "Swap"),
                    ("MINT", "Mint"),
                    ("BURN", "Burn"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
                verbose_name="Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="userpoints",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="userpoints",
            name="device_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Device ID"
            ),
        ),
        migrations.AlterField(
            model_name="userpoints",
            name="total_points",
            field=models.IntegerField(default=0, verbose_name="Total Points"),
        ),
        migrations.AlterField(
            model_name="userpoints",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="wallet_avatars/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="chain",
            field=models.CharField(max_length=20, verbose_name="Blockchain"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="device_id",
            field=models.CharField(max_length=100, verbose_name="Device ID"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="encrypted_private_key",
            field=models.TextField(
                blank=True, null=True, verbose_name="Encrypted Private Key"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_imported",
            field=models.BooleanField(default=False, verbose_name="Is Imported Wallet"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="is_watch_only",
            field=models.BooleanField(
                default=False, verbose_name="Is Watch-Only Wallet"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Wallet Name"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
        ),
    ]
