# Generated by Django 4.2.18 on 2025-03-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_mnemonicbackup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, verbose_name="设备ID")),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
                ),
                (
                    "points_awarded",
                    models.IntegerField(default=0, verbose_name="获得积分"),
                ),
            ],
            options={
                "verbose_name": "任务历史",
                "verbose_name_plural": "任务历史",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="code",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_repeatable",
        ),
        migrations.RemoveField(
            model_name="task",
            name="stages_config",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
        migrations.AddField(
            model_name="task",
            name="daily_limit",
            field=models.IntegerField(default=1, verbose_name="每日限制次数"),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, verbose_name="任务描述"),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, verbose_name="任务名称"),
        ),
        migrations.AlterField(
            model_name="task",
            name="points",
            field=models.IntegerField(default=0, verbose_name="奖励积分"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.DeleteModel(
            name="UserTask",
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.task",
                verbose_name="任务",
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["device_id", "task", "completed_at"],
                name="wallet_task_device__d9d8d3_idx",
            ),
        ),
    ]
