# Generated by Django 4.2.18 on 2025-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_tokenindex_is_token_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="discord",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Discord"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="fully_diluted_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=65,
                null=True,
                verbose_name="完全稀释价值",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="github",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Github"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="medium",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Medium"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="total_supply",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=65,
                null=True,
                verbose_name="总供应量",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="total_supply_formatted",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="格式化的总供应量"
            ),
        ),
    ]
