# Generated by Django 4.2.18 on 2025-02-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0005_token_discord_token_fully_diluted_value_token_github_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="token",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="token",
            name="is_native",
            field=models.BooleanField(default=False, verbose_name="是否原生代币"),
        ),
        migrations.AddField(
            model_name="token",
            name="last_balance",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="最后余额"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="last_price",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="最后价格"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="last_price_change",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="最后24h价格变化"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="last_value",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="最后价值"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="possible_spam",
            field=models.BooleanField(default=False, verbose_name="是否可能是垃圾代币"),
        ),
        migrations.AddField(
            model_name="token",
            name="security_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="安全评分"),
        ),
        migrations.AddField(
            model_name="token",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="是否验证"),
        ),
        migrations.AlterField(
            model_name="token",
            name="address",
            field=models.CharField(max_length=255, verbose_name="合约地址"),
        ),
        migrations.AlterField(
            model_name="token",
            name="contract_type",
            field=models.CharField(
                default="ERC20", max_length=20, verbose_name="合约类型"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="token",
            name="github",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="GitHub"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="logo",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="token",
            name="reddit",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Reddit"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(max_length=50, verbose_name="符号"),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_supply",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="总供应量"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_supply_formatted",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="格式化总供应量"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="website",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="网站"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("chain", "address")},
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["chain", "address"], name="wallet_toke_chain_298ab4_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="token",
            name="coin_id",
        ),
        migrations.RemoveField(
            model_name="token",
            name="development_status",
        ),
        migrations.RemoveField(
            model_name="token",
            name="explorer",
        ),
        migrations.RemoveField(
            model_name="token",
            name="first_data_at",
        ),
        migrations.RemoveField(
            model_name="token",
            name="fully_diluted_value",
        ),
        migrations.RemoveField(
            model_name="token",
            name="hardware_wallet",
        ),
        migrations.RemoveField(
            model_name="token",
            name="hash_algorithm",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="token",
            name="is_new",
        ),
        migrations.RemoveField(
            model_name="token",
            name="last_data_at",
        ),
        migrations.RemoveField(
            model_name="token",
            name="links_extended",
        ),
        migrations.RemoveField(
            model_name="token",
            name="open_source",
        ),
        migrations.RemoveField(
            model_name="token",
            name="org_structure",
        ),
        migrations.RemoveField(
            model_name="token",
            name="proof_type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="token",
            name="source_code",
        ),
        migrations.RemoveField(
            model_name="token",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="token",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="token",
            name="team",
        ),
        migrations.RemoveField(
            model_name="token",
            name="technical_doc",
        ),
        migrations.RemoveField(
            model_name="token",
            name="whitepaper_link",
        ),
        migrations.RemoveField(
            model_name="token",
            name="whitepaper_thumbnail",
        ),
    ]
