# Generated by Django 4.2.18 on 2025-03-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_taskhistory_alter_task_options_remove_task_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="code",
            field=models.CharField(
                default="DEFAULT_TASK",
                max_length=50,
                unique=True,
                verbose_name="任务代码",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_repeatable",
            field=models.BooleanField(default=False, verbose_name="是否可重复"),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                default="OTHER", max_length=50, verbose_name="任务类型"
            ),
        ),
    ]
