# Generated by Django 4.2.18 on 2025-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_task_code_task_is_repeatable_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stages_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="阶段配置"),
        ),
    ]
