# Generated by Django 4.2.18 on 2025-02-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_alter_token_unique_together_token_is_native_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="是否显示"),
        ),
    ]
