# Generated by Django 4.2.18 on 2025-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_token_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="coingecko_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="CoinGecko ID"
            ),
        ),
    ]
