# Generated by Django 4.2.18 on 2025-03-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_task_stages_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskhistory",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
        ),
    ]
