# Generated by Django 4.2.18 on 2025-03-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_taskhistory_extra_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sharetasktoken",
            options={
                "verbose_name": "代币分享任务",
                "verbose_name_plural": "代币分享任务",
            },
        ),
        migrations.RemoveField(
            model_name="sharetasktoken",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="sharetasktoken",
            name="start_time",
        ),
        migrations.AddField(
            model_name="sharetasktoken",
            name="official_tweet_id",
            field=models.CharField(
                blank=True,
                help_text="官方推文ID",
                max_length=100,
                null=True,
                verbose_name="官方推文ID",
            ),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="daily_limit",
            field=models.IntegerField(default=1, verbose_name="每日限制次数"),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="points",
            field=models.IntegerField(default=0, verbose_name="奖励积分"),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wallet.token"
            ),
        ),
        migrations.AlterField(
            model_name="sharetasktoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
