# Generated by Django 4.2.18 on 2025-02-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_token_coingecko_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenIndex",
        ),
    ]
