# Generated by Django 4.2.18 on 2025-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0009_delete_tokenindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=10, verbose_name="链")),
                ("address", models.CharField(max_length=255, verbose_name="合约地址")),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("symbol", models.CharField(max_length=50, verbose_name="符号")),
                ("decimals", models.IntegerField(default=18, verbose_name="小数位数")),
                (
                    "is_native",
                    models.BooleanField(default=False, verbose_name="是否原生代币"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "代币索引",
                "verbose_name_plural": "代币索引",
                "indexes": [
                    models.Index(
                        fields=["chain", "address"], name="wallet_toke_chain_fd34fc_idx"
                    ),
                    models.Index(
                        fields=["symbol"], name="wallet_toke_symbol_ab941d_idx"
                    ),
                    models.Index(fields=["name"], name="wallet_toke_name_56a71f_idx"),
                ],
                "unique_together": {("chain", "address")},
            },
        ),
    ]
