# Generated by Django 4.2.18 on 2025-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0011_tokenindexreport_tokenindexsource_tokenindexmetrics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ["-is_recommended", "-verified", "-created_at"],
                "verbose_name": "代币",
                "verbose_name_plural": "代币",
            },
        ),
        migrations.AddField(
            model_name="token",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="是否推荐"),
        ),
    ]
