# Generated by Django 4.2.18 on 2025-02-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0014_token_block_number_token_categories_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("chain", "tx_hash", "wallet")},
        ),
    ]
