# Generated by Django 4.2.18 on 2025-02-17 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0015_alter_transaction_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nftcollection",
            options={
                "ordering": ["-floor_price_usd", "-created_at"],
                "verbose_name": "NFT合集",
                "verbose_name_plural": "NFT合集",
            },
        ),
        migrations.RemoveField(
            model_name="nftcollection",
            name="discord",
        ),
        migrations.RemoveField(
            model_name="nftcollection",
            name="is_recommended",
        ),
        migrations.RemoveField(
            model_name="nftcollection",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="nftcollection",
            name="volume_24h",
        ),
        migrations.RemoveField(
            model_name="nftcollection",
            name="website",
        ),
        migrations.AddField(
            model_name="nftcollection",
            name="contract_type",
            field=models.CharField(
                default="ERC721", max_length=20, verbose_name="合约类型"
            ),
        ),
        migrations.AddField(
            model_name="nftcollection",
            name="floor_price_currency",
            field=models.CharField(
                default="eth", max_length=10, verbose_name="地板价币种"
            ),
        ),
        migrations.AddField(
            model_name="nftcollection",
            name="floor_price_usd",
            field=models.DecimalField(
                decimal_places=18,
                default=Decimal("0"),
                max_digits=30,
                verbose_name="地板价(USD)",
            ),
        ),
        migrations.AddField(
            model_name="nftcollection",
            name="is_spam",
            field=models.BooleanField(default=False, verbose_name="是否垃圾合集"),
        ),
    ]
