# Generated by Django 4.2.18 on 2025-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0016_alter_nftcollection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nftcollection",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="是否隐藏"),
        ),
    ]
