# Generated by Django 4.2.18 on 2025-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0017_nftcollection_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nftcollection",
            name="is_hidden",
        ),
        migrations.AddField(
            model_name="nftcollection",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="是否显示"),
        ),
    ]
