# Generated by Django 4.2.18 on 2025-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0018_remove_nftcollection_is_hidden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nftcollection",
            name="symbol",
            field=models.CharField(max_length=100, verbose_name="合集符号"),
        ),
    ]
