# Generated by Django 4.2.18 on 2025-02-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_add_nft_transfer_type"),
        ("wallet", "0020_alter_transaction_tx_type"),
    ]

    operations = []
