# Generated by Django 4.2.18 on 2025-02-25 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0022_add_biometric_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mnemonicbackup",
            name="chain",
            field=models.CharField(
                max_length=20, verbose_name="区块链"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "转账"),
                    ("APPROVE", "授权"),
                    ("SWAP", "兑换"),
                    ("MINT", "铸造"),
                    ("BURN", "销毁"),
                    ("OTHER", "其他"),
                ],
                max_length=20,
                verbose_name="交易类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mnemonicbackup",
            unique_together={("device_id", "chain")},
        ),
    ]
